baseURL: https://jakobsrwebsite.netlify.app/
languageCode: en-us
title: Portfolio Website for Jakob Bollenberger
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Executive Summary
    subtitle: |-
      A review of asset classes for investors that want to diversify into potentially uncorrelated assets.
    title: Analysis of Asset Classes
  blog: {}
  contact:
    address: 
      - city: London
        country: UK
        street: Sussex Place - London Business School
        title: Adress
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jakobb.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 0043 676 9021999
        title: Phone
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    #enable: yes
    #quicklinks:
     # - alt: HTML5 UP
      #  text: 'Design: '
       # url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
       # url: https://www.twitter.com
      # - icon: fa-facebook
        # label: Facebook
       # url: https://www.facebook.com
     # - icon: fa-instagram
     #   label: Instagram
    #    url: https://www.instagram.com
     # - icon: fa-github
      #  label: GitHub
      #  url: https://www.github.com
      # - icon: fa-linkedin
      #  label: LinkedIn
      #  url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
  #  button1:
  #    - name: Get Started
  #      url: blogs
  #  button2:
  #    - name: Log In
  #      url: '#'
    links:
      - name: Motivation
        url: blogs/motivation
      - name: About me
        url: blogs/abme
    #  - name: Generic Blog
    #    url: blogs/ipsum
    #  - name: Elements
    #    url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: equities.jpg
        subtitle: a must have for diversified indexers
        title: Equities
        url: blogs/equities.rmd
      - image: fi.jpg
        subtitle: fixed income generates ... fixed income
        title: Bonds
        url: blogs/fi.rmd
      - image: re.jpg
        subtitle: if all goes wrong, you at least have a place to sleep
        title: Real Estate
        url: blogs/re.rmd
      - image: analysis.jpg
        subtitle: can we diversify using these assets?
        title: Analysis
        url: blogs/analysis
     # - image: pic05.jpg
    #    subtitle: Ipsum Dolor Sit Amet
    #    title: Consequat
    #    url: blogs/ipsum
     # - image: pic06.jpg
    #    subtitle: Feugiat Amet Tempus
    #    title: Etiam
    #    url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: no
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
